openapi: 3.0.0

info:
  title: Avaya Onecloud CPaaS
  description: Make communications happen anywhere
  version: "3.0.0"

servers:
  - url: https://api.zang.io/v2
    description: Production server

paths:
  "/Accounts/{AccountSid}/Lookups/Carrier{mediaTypeExtension}":
    post:
      description: Carrier Lookup
      summary: "shows information on billing name address for some phone number"
      tags:
      - Carrier Services

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'

      responses:
        '200':
          $ref: '#/components/responses/carrier200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                PhoneNumber:
                  type: string
                  description: Phone Number
    get:
      description: Carrier Lookup
      summary: "shows info on all carrier lookups associated with some account"
      tags:
      - Carrier Services

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'

      responses:
        '200':
          $ref: '#/components/responses/carrier200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

  "/Accounts/{AccountSid}/Lookups/Cnam{mediaTypeExtension}":
    post:
      description: CNAM Lookup
      summary: "shows a CNAM information on some phone number"
      tags:
      - Carrier Services

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'

      responses:
        '200':
          $ref: '#/components/responses/cnam200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                PhoneNumber:
                  type: string
                  description: Phone Number
    get:
      description: CNAM Lookup List
      summary: shows info on all CNAM lookups associated with some account
      tags:
      - Carrier Services

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'

      responses:
        '200':
          $ref: '#/components/responses/cnam200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

  "/Accounts/{AccountSid}/Lookups/Bna{mediaTypeExtension}":
    post:
      description: BNA Lookup
      summary: "shows information on billing name address for some phone number"
      tags:
      - Carrier Services

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'

      responses:
        '200':
          $ref: '#/components/responses/bna200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                PhoneNumber:
                  type: string
                  description: Phone Number
    get:
      description: BNA Lookup List
      summary: shows info on all BNA lookups associated with some account
      tags:
      - Carrier Services

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'

      responses:
        '200':
          $ref: '#/components/responses/bna200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  parameters:
    PageSize:
      in: query
      name: PageSize
      description: >
            Used to specify the amount of list items to return per page.
      schema:
        type: integer
      required: false

    Page:
      in: query
      name: Page
      description: >
            Used to return a particular page within the list.
      schema:
        type: integer
      required: false

    MediaExt:
      description: >
            By default, Avaya's REST API returns XML. You may obtain CSV, JSON
            or XML by appending ".csv", ".json", or ".xml".
      in: path
      name: mediaTypeExtension
      required: true
      schema:
        type: string
        enum:
          - .xml
          - .json
          - .csv
        default: .xml

    AccSid:
      name: AccountSid
      description: >
            Your Account Sid
      in: path
      required: true
      schema:
        type: string

    CountryCode:
      name: CountryCode
      description: >
            Country Code
      in: path
      required: true
      schema:
        type: string

  schemas:
    carrierLookup:
      type: object
      description: Object containing carrier information
      properties:
        phone_number:
          description: The phone number the lookup was performed on.
          example: E164
          type: string
        date_updated:
          description: The date the lookup resource was last updated.
          example: Thu, 30 Oct 2014 08:35:27 -0000
          type: string
        price:
          description: The price to perform the lookup. If only the city and state of the number are looked up, you are charged $.01. If a full address lookup is successful you are charged $.15.
          example: $0.05
          type: string
        carrier_id:
          description: Four to Five digit Carrier Identification Code.
          example: 23123
          type: integer
        country_code:
          description: The iso country code of the mobile number.
          example: US
          type: string
        network:
          description: The carrier the phone number is currently operating on.
          example: Bandwidth 365
          type: string
        mobile:
          description: Boolean value specifying whether the phone number is mobile.
          example: true
          type: string
        uri:
          description: The Uniform Resource Identifier to this resource.
          example: /Accounts/{AccountSid}/Lookups/{LookupSid}
          type: string
        account_sid:
          description: An alphanumeric string identifying the account this lookup occurred through.
          example: AccountSid
          type: string
        sid:
          description: An alphanumeric string identifying this resource.
          example: CarrierLookupSid
          type: string
        date_created:
          description: The date the lookup resource was created.
          example: Thu, 30 Oct 2014 08:35:27 -0000
          type: string
        api_version:
          description: The API version being used when the carrier lookup was made.
          example: v2
          type: string

    cnamLookup:
      type: object
      description: Object containing CNAM information
      properties:
        phone_number:
          description: The phone number the lookup was performed on.
          example: E164
          type: string
        body:
          description: The result of our CNAM lookup. Usually a name or organisation associated with this phone.
          example: John Doe
          type: string
        sid:
          description: An alphanumeric string identifying this resource.
          example: BnaLookupSid
          type: string
        date_updated:
          description: The date the lookup resource was last updated.
          example: Thu, 30 Oct 2014 08:35:27 -0000
          type: string
        date_created:
          description: The date the lookup resource was created.
          example: Thu, 30 Oct 2014 08:35:27 -0000
          type: string
        price:
          description: The price to perform the lookup. If only the city and state of the number are looked up, you are charged $.01. If a full address lookup is successful you are charged $.15.
          example: $0.05
          type: string
        uri:
          description: The Uniform Resource Identifier to this resource.
          example: /Accounts/{AccountSid}/BNA/{BnaLookupSid}
          type: string
        api_version:
          description: The API version being used when the carrier lookup was made.
          example: v2
          type: string
        account_sid:
          description: An alphanumeric string identifying the account this lookup occurred through.
          example: AccountSid
          type: string

    bnaLookup:
      type: object
      description: Object containing BNA information
      properties:
        phone_number:
          description: The phone number the lookup was performed on.
          example: E164
          type: string
        sid:
          description: An alphanumeric string identifying this resource.
          example: BnaLookupSid
          type: string
        date_updated:
          description: The date the lookup resource was last updated.
          example: Thu, 30 Oct 2014 08:35:27 -0000
          type: string
        date_created:
          description: The date the lookup resource was created.
          example: Thu, 30 Oct 2014 08:35:27 -0000
          type: string
        price:
          description: The price to perform the lookup. If only the city and state of the number are looked up, you are charged $.01. If a full address lookup is successful you are charged $.15.
          example: $0.05
          type: string
        uri:
          description: The Uniform Resource Identifier to this resource.
          example: /Accounts/{AccountSid}/BNA/{BnaLookupSid}
          type: string
        api_version:
          description: The API version being used when the carrier lookup was made.
          example: v2
          type: string
        account_sid:
          description: An alphanumeric string identifying the account this lookup occurred through.
          example: AccountSid
          type: string
        city:
          description: The city associated with this phone number.
          example: Toronto
          type: string
        state:
          description: The state associated with this phone number.
          example: ON
          type: string
        zip_code:
          description: The zip code associated with this phone number.
          example: M1K4Z7
          type: string
        country_code:
          description: The country code associated with this phone number. (BNA lookups are currently only available in NA).
          example: US
          type: string

  responses:
    carrier200:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              first_page_uri:
                type: string
                description: URI for the first page of results.
              carrier_lookups:
                type: array
                description: Array containing Carrier Lookup.
                items:
                  $ref: '#/components/schemas/carrierLookup'
              end:
                type: integer
                description: Last result index.
              total:
                type: integer
                description: Number of items.
              previous_page_uri:
                type: string
                description: URI for the previous page of results.
              num_pages:
                type: integer
                description: Number of pages.
              uri:
                type: string
                description: The Uniform Resource Identifier to this resource.
              page_size:
                type: integer
                description: Number of items on a single page.
              start:
                type: integer
                description: Index of the first item on the current page.
              next_page_uri:
                type: string
                description: URI for the next page of the results.
              last_page_uri:
                type: string
                description: URI for the last page of the results.
              page:
                type: integer
                description: Current page number.
    cnam200:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              first_page_uri:
                type: string
                description: URI for the first page of results.
              cnam_lookups:
                type: array
                description: Array containing CNAM Lookup.
                items:
                  $ref: '#/components/schemas/cnamLookup'
              end:
                type: integer
                description: Last result index.
              total:
                type: integer
                description: Number of items.
              previous_page_uri:
                type: string
                description: URI for the previous page of results.
              num_pages:
                type: integer
                description: Number of pages.
              uri:
                type: string
                description: The Uniform Resource Identifier to this resource.
              page_size:
                type: integer
                description: Number of items on a single page.
              start:
                type: integer
                description: Index of the first item on the current page.
              next_page_uri:
                type: string
                description: URI for the next page of the results.
              last_page_uri:
                type: string
                description: URI for the last page of the results.
              page:
                type: integer
                description: Current page number.
    bna200:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              first_page_uri:
                type: string
                description: URI for the first page of results.
              end:
                type: integer
                description: Last result index.
              total:
                type: integer
                description: Number of items.
              previous_page_uri:
                type: string
                description: URI for the previous page of results.
              num_pages:
                type: integer
                description: Number of pages.
              uri:
                type: string
                description: The Uniform Resource Identifier to this resource.
              page_size:
                type: integer
                description: Number of items on a single page.
              start:
                type: integer
                description: Index of the first item on the current page.
              next_page_uri:
                type: string
                description: URI for the next page of the results.
              last_page_uri:
                type: string
                description: URI for the last page of the results.
              page:
                type: integer
                description: Current page number.
              bna_lookups:
                type: array
                description: Array containing BNA Lookup.
                items:
                  $ref: '#/components/schemas/bnaLookup'
    400:
      description: Bad Request
    401:
      description: The supplied credentials, if any, are not sufficient to access the resource.
    404:
      description: The requested resource was not found
    500:
      description: Internal server error.