openapi: 3.0.0

info:
  title: Avaya Onecloud CPaaS
  description: Make communications happen anywhere
  version: "3.0.0"

servers:
  - url: https://api.zang.io/v2
    description: Production server
  - url: https://api.zang.io/v3
    description: Production V3 Beta
  - url: https://api.zangsandbox.com/v2
    description: Sandbox server
  - url: https://api.zangsandbox.com/v3
    description: Sandbox V3 Beta
  - url: https://apik.zang.io/v2
    description: Staging server
  - url: https://apik.zang.io/v3
    description: Staging V3 Beta

paths:
  "/Accounts/{AccountSid}/Conferences{mediaTypeExtension}":
    get:
      description: List Conferences
      summary: "Shows information on all conferences associated with some account"
      tags:
      - Conferences

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/FriendlyName'
        - $ref: '#/components/parameters/Status'
        - $ref: '#/components/parameters/DateCreated'
        - $ref: '#/components/parameters/DateUpdated'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'

      responses:
        '200':
          $ref: '#/components/responses/listconf200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  "/Accounts/{AccountSid}/Conferences/{ConferenceSid}{mediaTypeExtension}":
    get:
      description: View Conference
      summary: "Shows information on some conference"
      tags:
      - Conferences

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/ConfSid'

      responses:
        '200':
          $ref: '#/components/responses/viewconf200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  "/Accounts/{AccountSid}/Conferences/{ConferenceSid}/Participants{mediaTypeExtension}":
    get:
      description: List Participants
      summary: "Lists all participants on some conference"
      tags:
      - Conferences

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/ConfSid'
        - $ref: '#/components/parameters/Muted'
        - $ref: '#/components/parameters/Deaf'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'

      responses:
        '200':
          $ref: '#/components/responses/listpart200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

  "/Accounts/{AccountSid}/Conferences/{ConferenceSid}/Participants/{ParticipantSid}{mediaTypeExtension}":
    get:
      description: View Participant
      summary: "Shows info on some conference participant"
      tags:
      - Conferences

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/ConfSid'
        - $ref: '#/components/parameters/PartSid'

      responses:
        '200':
          $ref: '#/components/responses/viewpart200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    post:
      description: Mute/Deafen Participant
      summary: "Mutes or deafens conference participant"
      tags:
      - Conferences

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/ConfSid'
        - $ref: '#/components/parameters/PartSid'

      responses:
        '200':
          $ref: '#/components/responses/viewpart200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                Muted:
                  type: boolean
                  description: Specifies whether the participant should be muted. Allowed values are "true" and "false".
                Deaf:
                  type: boolean
                  description: Specifies whether the participant should be deafened. Allowed values are "true" and "false"
    delete:
      description: Hang up Participant
      summary: "Hangs up a conference participant"
      tags:
      - Conferences

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/ConfSid'
        - $ref: '#/components/parameters/PartSid'

      responses:
        '200':
          $ref: '#/components/responses/viewpart200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

  "/Accounts/{AccountSid}/Conferences/{ConferenceSid}/Participants/{ParticipantSid}/Play{mediaTypeExtension}":
    post:
      description: Play Audio to Participant
      summary: "Plays an audio file to a conference participant"
      tags:
      - Conferences

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/ConfSid'
        - $ref: '#/components/parameters/PartSid'

      responses:
        '200':
          $ref: '#/components/responses/viewpart200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                AudioUrl:
                  type: string
                  description: A URL to the audio file that will be played. Mutliple AudioUrl parameters may be passed to play more than one file.
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  parameters:
    Muted:
      in: query
      name: Muted
      description: >
            Filter by participants that are muted. Allowed values are "true" or "false".
      schema:
        type: boolean
      required: false
    Deaf:
      in: query
      name: Deaf
      description: >
            Filter by participants that are deaf. Allowed values are "true" or "false".
      schema:
        type: boolean
      required: false
    FriendlyName:
      in: query
      name: FriendlyName
      description: >
            Filters conferences by the given FriendlyName.
      schema:
        type: string
      required: false
    Status:
      in: query
      name: Status
      description: >
            Filters conferences by the given status. Allowed values are "init", "in-progress", or "completed".
      schema:
        type: string
      required: false
    DateCreated:
      in: query
      name: DateCreated
      description: >
            Filter by conferences created on, after, or before a given date. Date range can be specified using inequalities like "DateCreated>=YYYY-MM-DD". Allowed values are dates in the YYYY-MM-DD format..
      schema:
        type: string
      required: false
    DateUpdated:
      in: query
      name: DateUpdated
      description: >
            Filter by conferences updated on or after a given date. Date range can be specified using inequalities like "DateCreated>=YYYY-MM-DD". Allowed values are dates in the YYYY-MM-DD format.
      schema:
        type: string
      required: false
    PageSize:
      in: query
      name: PageSize
      description: >
            Used to specify the amount of list items to return per page.
      schema:
        type: integer
      required: false
    Page:
      in: query
      name: Page
      description: >
            Used to return a particular page within the list.
      schema:
        type: integer
      required: false
    PartSid:
      name: ParticipantSid
      description: >
          Participant Sid.
      in: path
      required: true
      schema:
        type: string
    ConfSid:
      name: ConferenceSid
      description: >
          Conference Sid.
      in: path
      required: true
      schema:
        type: string
    AccSid:
      name: AccountSid
      description: >
            Your Account Sid.
      in: path
      required: true
      schema:
        type: string
    MediaExt:
      description: >
            By default, Avaya's REST API returns XML. You may obtain CSV, JSON
            or XML by appending ".csv", ".json", or ".xml".
      in: path
      name: mediaTypeExtension
      required: true
      schema:
        type: string
        enum:
          - .xml
          - .json
          - .csv
        default: .xml
  schemas:
    viewpart:
      type: object
      required:
        - date_updated
        - deaf
        - caller_number
        - caller_name
        - duration
        - conference_sid
        - muted
        - uri
        - account_sid
        - call_sid
        - sid
        - date_created
      properties:
        date_updated:
          type: string
          description: The date the participant was last updated.
          example: Tue, 10 Dec 2019 20:34:45 -0000
        deaf:
          type: string
          description: Specifies if participant is deafened. Allowed values are "true" or "false".
          example: false
        caller_number:
          type: string
          description: The number of the caller.
          example: "14166144164"
        caller_name:
          type: string
          description: The Caller-ID of the caller.
          example: Bob
        duration:
          type: integer
          description: The duration of how long the participant has been on the conference.
          example: 50
        conference_sid:
          type: string
          description: An alphanumeric string identifying this resource.
          example: ConferenceSid
        muted:
          type: string
          description: Specifies if participant is muted. Allowed values are "true" or "false".
          example: false
        uri:
          type: string
          description: The URI for this resource.
          example: /Accounts/{AccountSid}/Conferences/{ConferenceSid}/Participants/{ParticipantSid}.json
        account_sid:
          type: string
          description: An alphanumeric string identifying the account the conference occurred through.
          example: AccountSid
        call_sid:
          type: string
          description: An alphanumeric string identifying the call the conference occurred through.
          example: CallSid
        sid:
          type: string
          description: An alphanumeric string identifying this resource.
          example: ParticipantSid
        date_created:
          type: string
          description: The date the participant entered the conference.
          example: Tue, 10 Dec 2019 20:34:11 -0000
    viewconf:
      type: object
      required:
        - status
        - subresource_uris
        - sid
        - date_updated
        - date_created
        - active_participants_count
        - friendly_name
        - uri
        - account_sid
      properties:
        status:
          type: string
          description: Conference status. Possible values are “init”, “in-progress” or “completed”. “init” means the conference has been initialize, but no one has yet entered.
          example: completed
        subresource_uris:
          type: object
          description: URIs for managing this resource.
          properties:
            participants:
              description: URI for managing participants.
              example: /Accounts/{AccountSid}/Conferences/{ConferenceSid}/Participants.json
              type: string
        sid:
          type: string
          description: An alphanumeric string identifying this resource.
          example: ConferenceSid
        date_updated:
          type: string
          description: The date the conference was last updated.
          example: Tue, 10 Dec 2019 20:34:45 -0000
        date_created:
          type: string
          description: The date the conference was created.
          example: Tue, 10 Dec 2019 20:34:11 -0000
        active_participants_count:
          type: integer
          description: The number of participants currently connected to conference.
          example: 1
        friendly_name:
          type: string
          description: User generated name of the conference.
          example: ExampleConferenceName
        uri:
          type: string
          description: The URI for this resource.
          example: ApplicationSid
        account_sid:
          type: string
          description: An alphanumeric string identifying the account the conference occurred through.
          example: AccountSid
  responses:
    listpart200:
      description: OK
      content:
        application/json:
          schema:
            type: object
            required:
              - first_page_uri
              - end
              - total
              - previous_page_uri
              - num_pages
              - uri
              - page_size
              - start
              - participants
              - next_page_uri
              - last_page_uri
              - page
            properties:
              first_page_uri:
                type: string
                description: URI for the first page of results.
                example: /Accounts/{AccountSid}/Conferences/{ConferenceSid}/Participants.json?Page=0&PageSize=50
              end:
                type: integer
                description: Last result index.
                example: 3
              total:
                type: integer
                description: Number of items.
                example: 4
              previous_page_uri:
                type: string
                description: URI for the previous page of results.
                example: /Accounts/{AccountSid}/Conferences/{ConferenceSid}/Participants.json?Page=0&PageSize=50
              num_pages:
                type: integer
                description: Number of pages.
                example: 1
              uri:
                type: string
                description: The Uniform Resource Identifier to this resource.
                example: /Accounts/{AccountSid}/Conferences/{ConferenceSid}/Participants.json
              page_size:
                type: integer
                description: Number of items on a single page.
                example: 50
              start:
                type: integer
                description: Index of the first item on the current page.
                example: 0
              participants:
                type: array
                description: Array containing participants.
                items:
                  $ref: '#/components/schemas/viewpart'
              next_page_uri:
                type: string
                description: URI for the next page of the results.
                example: /Accounts/{AccountSid}/Conferences/{ConferenceSid}/Participants.json?Page=1&PageSize=50
              last_page_uri:
                type: string
                description: URI for the last page of the results.
                example: /Accounts/{AccountSid}/Conferences/{ConferenceSid}/Participants.json?Page=1&PageSize=50
              page:
                type: integer
                description: Current page number.
                example: 0
    listconf200:
      description: OK
      content:
        application/json:
          schema:
            type: object
            required:
              - first_page_uri
              - conference
              - end
              - total
              - previous_page_uri
              - num_pages
              - uri
              - page_size
              - start
              - next_page_uri
              - last_page_uri
              - page
            properties:
              first_page_uri:
                type: string
                description: URI for the first page of results.
                example: /Accounts/{AccountSid}/Applications.json?Page=0&PageSize=50
              conferences:
                type: array
                description: Array containing conferences.
                items:
                  $ref: '#/components/schemas/viewconf'
              end:
                type: integer
                description: Last result index.
                example: 3
              total:
                type: integer
                description: Number of items.
                example: 4
              previous_page_uri:
                type: string
                description: URI for the previous page of results.
                example: /Accounts/{AccountSid}/Applications.json?Page=0&PageSize=50
              num_pages:
                type: integer
                description: Number of pages.
                example: 1
              uri:
                type: string
                description: The Uniform Resource Identifier to this resource.
                example: /Accounts/{AccountSid}/Applications.json
              page_size:
                type: integer
                description: Number of items on a single page.
                example: 50
              start:
                type: integer
                description: Index of the first item on the current page.
                example: 0
              next_page_uri:
                type: string
                description: URI for the next page of the results.
                example: /Accounts/{AccountSid}/Applications.json?Page=1&PageSize=50
              last_page_uri:
                type: string
                description: URI for the last page of the results.
                example: /Accounts/{AccountSid}/Applications.json?Page=1&PageSize=50
              page:
                type: integer
                description: Current page number.
                example: 0
    viewpart200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/viewpart'
    viewconf200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/viewconf'
    400:
      description: Bad Request
    401:
      description: The supplied credentials, if any, are not sufficient to access the resource.
    404:
      description: The requested resource was not found
    500:
      description: Internal server error.