openapi: 3.0.0

info:
  title: Avaya Onecloud CPaaS
  description: Make communications happen anywhere
  version: "2.0"

servers:
  - url: https://api.zang.io/v2
    description: Production server

paths:
  "/Accounts/{AccountSid}/Conferences{mediaTypeExtension}":
    get:
      description: List Conferences
      summary: "Shows information on all conferences associated with some account"
      tags:
      - Applications

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/FriendlyName'
        - $ref: '#/components/parameters/Status'
        - $ref: '#/components/parameters/DateCreated'
        - $ref: '#/components/parameters/DateUpdated'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'

      responses:
        '200':
          $ref: '#/components/responses/listconf200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    post:
      description: Create Applications
      summary: "Creates a new application"
      tags:
      - Applications

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'

      responses:
        '200':
          $ref: '#/components/responses/viewapp200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/reqapp'

  "/Accounts/{AccountSid}/Applications/{ApplicationSid}{mediaTypeExtension}":
    get:
      description: View Application
      summary: "Shows info on all Avaya CPaaS applications associated with some account"
      tags:
      - Applications

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/AppSid'

      responses:
        '200':
          $ref: '#/components/responses/viewapp200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    post:
      description: Update Application
      summary: "Updates Avaya CPaaS application data"
      tags:
      - Applications

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/AppSid'

      responses:
        '200':
          $ref: '#/components/responses/viewapp200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/reqapp'
    delete:
      description: Delete Application
      summary: "Deletes Avaya CPaaS application"
      tags:
      - Applications

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/AppSid'

      responses:
        '200':
          $ref: '#/components/responses/viewapp200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'


components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  parameters:
    FriendlyName:
      in: query
      name: FriendlyName
      description: >
            Filters conferences by the given FriendlyName.
      schema:
        type: string
      required: false
    Status:
      in: query
      name: Status
      description: >
            Filters conferences by the given status. Allowed values are "init", "in-progress", or "completed".
      schema:
        type: string
      required: false
    DateCreated:
      in: query
      name: DateCreated
      description: >
            Filter by conferences created on, after, or before a given date. Date range can be specified using inequalities like "DateCreated>=YYYY-MM-DD". Allowed values are dates in the YYYY-MM-DD format..
      schema:
        type: string
      required: false
    DateUpdated:
      in: query
      name: DateUpdated
      description: >
            Filter by conferences updated on or after a given date. Date range can be specified using inequalities like "DateCreated>=YYYY-MM-DD". Allowed values are dates in the YYYY-MM-DD format.
      schema:
        type: string
      required: false
    PageSize:
      in: query
      name: PageSize
      description: >
            Used to specify the amount of list items to return per page.
      schema:
        type: integer
      required: false
    Page:
      in: query
      name: Page
      description: >
            Used to return a particular page within the list.
      schema:
        type: integer
      required: false
    AccSid:
      name: AccountSid
      description: >
            Your Account Sid
      in: path
      required: true
      schema:
        type: string
    MediaExt:
      description: >
            By default, Avaya's REST API returns XML. You may obtain CSV, JSON
            or HTML by appending ".csv", ".json", or ".html".
      in: path
      name: mediaTypeExtension
      required: true
      schema:
        type: string
        enum:
          - .xml
          - .json
          - .csv
          - .html
        default: .xml
  schemas:
    reqapp:
      type: object
      properties:
        FriendlyName:
          type: string
          description: The name used to identify this application. If this is not included at the initial POST, it is given the value of the application sid.
          example: ExampleApplication
        voice_url:
          type: string
          description: The URL requested once the call connects. This URL must be valid and should return InboundXML containing instructions on how to process your call. A badly formatted Url will NOT fallback to the FallbackUrl but return an error without placing the call. Url length is limited to 200 characters.
          example: www.example.com/voicerequest
        voice_method:
          type: string
          description: The HTTP method used to request the URL once the call connects. Valid parameters are GET and POST - any other value will default to POST.
          example: POST
        voice_fallback_url:
          type: string
          description: URL used if the required URL is unavailable or if any errors occur during execution of the InboundXML returned by the required URL. Url length is limited to 200 characters.
          example: www.example.com/voicefallback
        voice_fallback_method:
          type: string
          description: The HTTP method used to request the FallbackUrl once the call connects. Valid parameters are GET and POST - any other value will default to POST.
          example: POST
        voice_caller_id_lookup:
          type: boolean
          description: Look up the caller’s caller-ID name from the CNAM database (additional charges apply). Allowed values are "true" and "false".
          example: true
        sms_url:
          type: string
          description: The URL requested when an SMS is received. This URL must be valid and should return InboundXML containing instructions on how to process the SMS. A badly formatted URL will NOT fallback to the FallbackUrl but return an error without placing the call. URL length is limited to 200 characters.
          example: www.example.com/smsrequest
        sms_method:
          type: string
          description: The HTTP method used to request the URL when an SMS is received. Valid parameters are GET and POST - any other value will default to POST.
          example: POST
        sms_fallback_url:
          type: string
          description: URL used if the required URL is unavailable or if any errors occur during execution of the InboundXML returned by the required URL. Url length is limited to 200 characters.
          example: www.example.com/smsfallback
        sms_fallback_method:
          type: string
          description: The HTTP method used to request the FallbackUrl once the call connects. Valid parameters are GET and POST - any other value will default to POST.
          example: POST
        mms_url:
          type: string
          description: The URL returning InboundXML incoming phone numbers should execute when receiving an mms.
          example: www.example.com/mmsrequest
        mms_method:
          type: string
          description: The HTTP method used when making requests to the MmsUrl. Valid parameters are GET and POST - any other value will default to POST.
          example: POST
        mms_fallback_url:
          type: string
          description: URL used if any errors occur during execution of InboundXML from an sms or at initial request of the MmsUrl. Url length is limited to 200 characters.
          example: www.example.com/mmsfallback
        mms_fallback_method:
          type: string
          description: Specifies the HTTP method (GET or POST) used to request the MmsFallbackUrl. Valid parameters are GET and POST - any other value will default to POST.
          example: POST
        date_updated:
          type: string
          description: The date the number was last updated.
          example: Mon, 30 Jul 2012 16:53:23 +0000
        client_count:
          type: integer
          description: number of DID's using this application.
          example: 1
        sid:
          type: string
          description: An alphanumeric string identifying this resource.
          example: ApplicationSid
        heartbeat_method:
          type: string
          description: The HTTP method Avaya CPaaS will use when requesting the HeartbeatURL. Either GET or POST.
          example: GET

        status_callback_method:
          type: string
          description: URI for the last page of the results.
          example: POST
        hangup_callback:
          type: string
          description: This is a StatusCallback clone that will be phased out in future versions.
          example: www.example.com/hangupcallback
        hangup_callback_method:
          type: string
          description: This is a StatusCallbackMethod clone that will be phased out in future versions.
          example: POST
        heartbeat_url:
          type: string
          description: URL that can be used to monitor the phone number.
          example: www.example.com/heartbeat
        friendly_name:
          type: string
          description: A human-readable name associated with this domain.
          example: TestApplication
        uri:
          type: string
          description: The Uniform Resource Identifier to this resource.
          example: /Accounts/{AccountSid}/Applications/{ApplicationSid}

        account_sid:
          type: string
          description: An alphanumeric string identifying the account associated with this resource.
          example: AccountSid

        api_version:
          type: string
          description: The API version used with this incoming number.
          example: v2

        date_created:
          type: string
          description: The date the number was procured by Avaya.
          example: Mon, 30 Jul 2012 16:53:23 +0000
        status_callback:
          type: string
          description: A URL that will be requested when the call connects and ends, sending information about the call.
          example: www.example.com/statuscallback
    viewapp:
      type: object
      properties:
        mms_url:
          type: string
          description: The URL returning InboundXML incoming phone numbers should execute when receiving an mms.
          example: www.example.com/mmsrequest
        date_updated:
          type: string
          description: The date the number was last updated.
          example: Mon, 30 Jul 2012 16:53:23 +0000
        mms_method:
          type: string
          description: The HTTP method used when making requests to the MmsUrl. Either GET or POST.
          example: POST
        voice_url:
          type: string
          description: The URL returning InboundXML incoming phone numbers should execute when receiving a call.
          example: www.example.com/voicerequest
        voice_fallback_method:
          type: string
          description: Specifies the HTTP method (GET or POST) used to request the VoiceFallbackUrl.
          example: POST
        client_count:
          type: integer
          description: number of DID's using this application.
          example: 1
        mms_fallback_method:
          type: string
          description: Specifies the HTTP method (GET or POST) used to request the MmsFallbackUrl.
          example: POST
        sid:
          type: string
          description: An alphanumeric string identifying this resource.
          example: ApplicationSid
        heartbeat_method:
          type: string
          description: The HTTP method Avaya CPaaS will use when requesting the HeartbeatURL. Either GET or POST.
          example: GET
        mms_fallback_url:
          type: string
          description: URL used if any errors occur during execution of InboundXML from an sms or at initial request of the MmsUrl.
          example: www.example.com/mmsfallback
        status_callback_method:
          type: string
          description: URI for the last page of the results.
          example: POST
        voice_fallback_url:
          type: string
          description: URL used if any errors occur during execution of InboundXML from an sms or at initial request of the VoiceUrl.
          example: www.example.com/voicefallback
        hangup_callback:
          type: string
          description: This is a StatusCallback clone that will be phased out in future versions.
          example: www.example.com/hangupcallback
        hangup_callback_method:
          type: string
          description: This is a StatusCallbackMethod clone that will be phased out in future versions.
          example: POST
        heartbeat_url:
          type: string
          description: URL that can be used to monitor the phone number.
          example: www.example.com/heartbeat
        sms_url:
          type: string
          description: The URL returning InboundXML incoming phone numbers should execute when receiving an sms.
          example: www.example.com/smsrequest
        voice_method:
          type: string
          description: The HTTP method used when making requests to the VoiceUrl. Either GET or POST.
          example: POST
        voice_caller_id_lookup:
          type: boolean
          description: Specifies if the incoming number has voice caller ID lookup enabled.
          example: true
        friendly_name:
          type: string
          description: A human-readable name associated with this domain.
          example: TestApplication
        uri:
          type: string
          description: The Uniform Resource Identifier to this resource.
          example: /Accounts/{AccountSid}/Applications/{ApplicationSid}
        sms_fallback_url:
          type: string
          description: URL used if any errors occur during execution of InboundXML from an sms or at initial request of the SmsUrl.
          example: www.example.com/smsfallback
        account_sid:
          type: string
          description: An alphanumeric string identifying the account associated with this resource.
          example: AccountSid
        sms_method:
          type: string
          description: The HTTP method used when making requests to the SmsUrl. Either GET or POST.
          example: POST
        api_version:
          type: string
          description: The API version used with this incoming number.
          example: v2
        sms_fallback_method:
          type: string
          description: Specifies the HTTP method (GET or POST) used to request the SmsFallbackUrl.
          example: POST
        date_created:
          type: string
          description: The date the number was procured by Avaya.
          example: Mon, 30 Jul 2012 16:53:23 +0000
        status_callback:
          type: string
          description: A URL that will be requested when the call connects and ends, sending information about the call.
          example: www.example.com/statuscallback
  responses:
    listconf200:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              first_page_uri:
                type: string
                description: URI for the first page of results.
                example: /Accounts/{AccountSid}/Applications.json?Page=0&PageSize=50
              conferences:
                type: array
                description: Array containing conferences.
                items:
                  $ref: '#/components/schemas/viewconf'
              end:
                type: integer
                description: Last result index.
                example: 3
              total:
                type: integer
                description: Number of items.
                example: 4
              previous_page_uri:
                type: string
                description: URI for the previous page of results.
                example: /Accounts/{AccountSid}/Applications.json?Page=0&PageSize=50
              num_pages:
                type: integer
                description: Number of pages.
                example: 1
              uri:
                type: string
                description: The Uniform Resource Identifier to this resource.
                example: /Accounts/{AccountSid}/Applications.json
              page_size:
                type: integer
                description: Number of items on a single page.
                example: 50
              start:
                type: integer
                description: Index of the first item on the current page.
                example: 0
              next_page_uri:
                type: string
                description: URI for the next page of the results.
                example: /Accounts/{AccountSid}/Applications.json?Page=1&PageSize=50
              last_page_uri:
                type: string
                description: URI for the last page of the results.
                example: /Accounts/{AccountSid}/Applications.json?Page=1&PageSize=50
              page:
                type: integer
                description: Current page number.
                example: 0
    viewapp200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/viewapp'
    400:
      description: Bad Request
    401:
      description: The supplied credentials, if any, are not sufficient to access the resource.
    404:
      description: The requested resource was not found
    500:
      description: Internal server error.