openapi: 3.0.0

info:
  title: Avaya Onecloud CPaaS
  description: Make communications happen anywhere
  version: "3.0.0"

servers:
  - url: https://api.zang.io/v2
    description: Production server
  - url: https://api.zang.io/v3
    description: Production V3 Beta
  - url: https://api.zangsandbox.com/v2
    description: Sandbox server
  - url: https://api.zangsandbox.com/v3
    description: Sandbox V3 Beta
  - url: https://apik.zang.io/v2
    description: Staging server
  - url: https://apik.zang.io/v3
    description: Staging V3 Beta

paths:
  "/Accounts/{AccountSid}/Recordings{mediaTypeExtension}":
    get:
      description: List Recordings
      summary: "shows info on all recordings associated with some account"
      tags:
      - Recordings

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'
        - $ref: '#/components/parameters/CallSid'
        - $ref: '#/components/parameters/DateCreated'

      responses:
        '200':
          $ref: '#/components/responses/rec200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

  "/Accounts/{AccountSid}/Recordings/{RecordingSid}{mediaTypeExtension}":
    get:
      description: View Recording
      summary: "shows information on some recording"
      tags:
      - Recordings

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/RecSid'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/recording'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

    delete:
      description: Delete Recording
      summary: "deletes recording"
      tags:
      - Recordings

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/RecSid'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'
        - $ref: '#/components/parameters/CallSid'
        - $ref: '#/components/parameters/DateCreated'

      responses:
        '200':
          $ref: '#/components/responses/rec200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

  "/Accounts/{AccountSid}/Calls/{CallSid}/Recordings{mediaTypeExtension}":
    post:
      description: Record Live Call
      summary: "options include time limit, file format, trimming silence and transcribing"
      tags:
      - Recordings

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/PathCallSid'

      responses:
        '200':
          $ref: '#/components/responses/postrec200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

      requestBody:
        required: false
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - Record
              properties:
                Record:
                  type: boolean
                  description: Specifies if a call recording should start or end. Allowed values are "true" to start recording and "false" to end recording. Any number of simultaneous, separate recordings can be initiated.
                Direction:
                  type: string
                  description: Specifies which audio stream to record. Allowed values are "in" to record the incoming caller's audio, "out" to record the outgoing caller's audio, and "both" to record both.
                TimeLimit:
                  type: integer
                  description: The maximum duration of the recording. Allowed value is an integer greater than 0.
                CallbackUrl:
                  type: string
                  description: A URL that will be requested when the recording ends, sending information about the recording. The longer the recording, the longer the delay in processing the recording and requesting the CallbackUrl. Url length is limited to 200 characters.
                FileFormat:
                  type: string
                  description: Specifies the file format of the recording. Allowed values are "mp3" or "wav" - any other value will default to "mp3".
                TrimSilence:
                  type: string
                  description: Trims all silence from the beginning of the recording. Allowed values are "true" or "false" - any other value will default to "false".
                Transcribe:
                  type: string
                  description: Specifies if this recording should be transcribed. Allowed values are "true" and "false" - all other values will default to "false".
                TranscribeQuality:
                  type: string
                  description: Specifies the quality of the transcription. Allowed values are "auto" for automated transcriptions and "hybrid" for human-reviewed transcriptions - all other values will default to "auto".
                TranscribeCallback:
                  type: string
                  description: A URL that will be requested when the call ends, sending information about the transcription. The longer the recording, the longer the delay in processing the transcription and requesting the TranscribeCallback. URL length is limited to 200 characters.

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  parameters:
    RecSid:
      in: path
      name: RecordingSid
      description: >
            Recording SID.
      schema:
        type: string
      required: true
    PageSize:
      in: query
      name: PageSize
      description: >
            Used to specify the amount of list items to return per page.
      schema:
        type: integer
      required: false
    Page:
      in: query
      name: Page
      description: >
            Used to return a particular page within the list.
      schema:
        type: integer
      required: false
    AccSid:
      name: AccountSid
      description: >
            Your Account Sid
      in: path
      required: true
      schema:
        type: string
    CallSid:
      name: CallSid
      description: >
            Call Sid
      in: query
      required: false
      schema:
        type: string
    PathCallSid:
      name: CallSid
      description: >
            Call Sid
      in: path
      required: true
      schema:
        type: string
    MediaExt:
      description: >
            By default, Avaya's REST API returns XML. You may obtain CSV, JSON
            or XML by appending ".csv", ".json", or ".xml".
      in: path
      name: mediaTypeExtension
      required: true
      schema:
        type: string
        enum:
          - .xml
          - .json
          - .csv
        default: .xml
    DateCreated:
      name: DateCreated
      description: >
            Lists all recordings created on or after a certain date. Date range can be specified using inequalities like so: DateCreated=>YYYY-MM-DD.
      in: query
      required: false
      schema:
        type: integer

  schemas:
    recording:
      type: object
      description: Object containing information on available phone numbers
      required:
        - duration
        - call_sid
        - sid
        - date_updated
        - date_created
        - price
        - recording_url
        - api_version
        - uri
      properties:
        duration:
          description: Time of recording in seconds.
          example: 0
          type: integer
        call_sid:
          description: The sid identifying the recorded call.
          example: CallSid
          type: string
        sid:
          description: An alphanumeric string identifying this resource.
          example: RecordingSid
          type: string
        date_updated:
          description: The date the credential list was last updated.
          example: Fri, 29 Nov 2019 15:42:30 -0000
          type: string
        date_created:
          description: The date this credential list was created.
          example: Fri, 29 Nov 2019 15:42:30 -0000
          type: string
        price:
          description: The cost of this recording.
          example: 0.05
          type: string
        recording_url:
          description: The URL where the mp3 file of the recording is located.
          example: http://recordings.example.com/RecordingSid.mp3
          type: string
        api_version:
          description: The API version used with this incoming number.
          example: v2
          type: string
        uri:
          description: The Uniform Resource Identifier to this resource.
          example: /Accounts/{AccountSid}/Recordings/{RecordingSid}.json
          type: string
  responses:
    rec200:
      description: OK
      content:
        application/json:
          schema:
            type: object
            required:
              - first_page_uri
              - recordings
              - end
              - total
              - previous_page_uri
              - num_pages
              - uri
              - page_size
              - start
              - next_page_uri
              - last_page_uri
              - page
            properties:
              first_page_uri:
                type: string
                description: URI for the first page of results.
              recordings:
                type: array
                description: Array containing information on available phone numbers.
                items:
                  $ref: '#/components/schemas/recording'
              end:
                type: integer
                description: Last result index.
              total:
                type: integer
                description: Number of items.
              previous_page_uri:
                type: string
                description: URI for the previous page of results.
              num_pages:
                type: integer
                description: Number of pages.
              uri:
                type: string
                description: The Uniform Resource Identifier to this resource.
              page_size:
                type: integer
                description: Number of items on a single page.
              start:
                type: integer
                description: Index of the first item on the current page.
              next_page_uri:
                type: string
                description: URI for the next page of the results.
              last_page_uri:
                type: string
                description: URI for the last page of the results.
              page:
                type: integer
                description: Current page number.
    postrec200:
      description: OK
      content:
        application/json:
          schema:
            type: object
            required:
              - date_updated
              - parent_call_sid
              - duration
              - from
              - to
              - caller_id_blocked
              - answered_by
              - sid
              - recordings_count
              - price
              - api_version
              - status
              - direction
              - start_time
              - date_created
              - subresource_uris
              - forwarded_from
              - uri
              - account_sid
              - duration_billed
              - end_time
              - phone_number_sid
            properties:
              date_updated:
                type: string
                description: The date the recording was last updated.
              parent_call_sid:
                type: string
                description: The sid of the parent call.
              duration:
                type: integer
                description: The length of the recording in seconds.
              from:
                type: string
                description: The number that initiated the call.
              to:
                type: string
                description: The number that was called.
              caller_id_blocked:
                type: string
                description: Specifies whether the caller ID of the inbound phone number was blocked.
              answered_by:
                type: string
                description: If the initiated call has answering machine detection, this specifies whether the machine answered. Can be "human", "machine" or "tbd" (to be determined).
              sid:
                type: string
                description: An alphanumeric string identifying this resource.
              recordings_count:
                type: integer
                description: The number of recordings made during this call.
              price:
                type: string
                description: The cost of the recording, if available.
              api_version:
                type: string
                description: The Api Version being used.
              status:
                type: string
                description: Status of the recording. May be in-progress, completed, or failed.
              direction:
                type: string
                description: Direction of the recording. May be in, out, or both
              start_time:
                type: integer
                description: The date and time the call started.
              date_created:
                type: integer
                description: The date the recording was created.
              subresource_uris:
                type: object
                description: List of a call's various subresources and their URL paths. Examples of call subresources are notifications, recordings, etc.
                properties:
                  notifications:
                    type: string
                    description: Uri of the corresponding notification.
                  recordings:
                    type: string
                    description: Uri of the corresponding recording.
              forwarded_from:
                type: string
                description: The number that forwarded the call, if any.
              uri:
                type: string
                description: The uri pointing to this resource.
              account_sid:
                type: string
                description: An alphanumeric string identifying the account this call occurred through.
              duration_billed:
                type: integer
                description: The billed length of the recording in seconds.
              end_time:
                type: string
                description: The date and time the recording ended.
              phone_number_sid:
                type: string
                description: The sid of the Avaya CPaaS number calling, or being called. If no Avaya CPaaS phone number is involved in the call, this property is empty.
    400:
      description: Bad Request
    401:
      description: The supplied credentials, if any, are not sufficient to access the resource.
    404:
      description: The requested resource was not found
    500:
      description: Internal server error.