openapi: 3.0.0

info:
  title: Avaya Onecloud CPaaS
  description: Make communications happen anywhere
  version: "2.0"

servers:
  - url: https://api.zang.io/v2
    description: Production server

paths:
  "/Accounts/{AccountSid}/SIP/IpAccessControlLists{mediaTypeExtension}":
    get:
      description: List IP ACL
      summary: "List all IP access control lists associated with a particular account"
      tags:
      - SIP IP Access Control List

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/IPACLSid'

      responses:
        '200':
          $ref: '#/components/responses/listacl200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    post:
      description: Create IP Access Control List
      summary: "Create IP access control list"
      tags:
      - SIP IP Access Control List

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/IPACLSid'

      responses:
        '200':
          $ref: '#/components/responses/viewacl200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

      requestBody:
        required: false
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - FriendlyName
              properties:
                FriendlyName:
                  type: string
                  description: A human-readable name associated with this IP ACL.

  "/Accounts/{AccountSid}/SIP/IpAccessControlLists/{IpAccessControlListSid}{mediaTypeExtension}":
    get:
      description: View IP Access Control List
      summary: "View information for IP access control list"
      tags:
      - SIP IP Access Control List

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/IPACLSid'

      responses:
        '200':
          $ref: '#/components/responses/viewacl200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

    post:
      description: Update IP Access Control List
      summary: "Update information for IP access control list"
      tags:
      - SIP IP Access Control List

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/IPACLSid'

      responses:
        '200':
          $ref: '#/components/responses/viewacl200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

      requestBody:
        required: false
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                FriendlyName:
                  type: string
                  description: A human-readable name associated with this IP ACL.
    delete:
      description: Delete IP Access Control List
      summary: "Delete IP access control list"
      tags:
      - SIP IP Access Control List

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/IPACLSid'

      responses:
        '200':
          $ref: '#/components/responses/viewacl200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

  "/Accounts/{AccountSid}/SIP/IpAccessControlLists/{IpAccessControlListSid}/IpAddresses{mediaTypeExtension}":
    get:
      description: List ACL IPs
      summary: "Lists IP addresses attached to some IP access control list"
      tags:
      - SIP IP Access Control List

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/IPACLSid'

      responses:
        '200':
          $ref: '#/components/responses/listip200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    post:
      description: Add ACL IP
      summary: "Add new IP for access control list"
      tags:
      - SIP IP Access Control List

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/IPACLSid'

      responses:
        '200':
          $ref: '#/components/responses/viewip200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - FriendlyName
                - IpAddress
              properties:
                FriendlyName:
                  type: string
                  description: A human-readable name associated with this IP ACL.
                IpAddress:
                  type: string
                  description: An IP address from which you wish to accept traffic.

  "/Accounts/{AccountSid}/SIP/IpAccessControlLists/{IpAccessControlListSid}/IpAddresses/{IpAddressSid}{mediaTypeExtension}":
    get:
      description: View ACL IP
      summary: "View information on IP access control list IP address"
      tags:
      - SIP IP Access Control List

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/IPACLSid'
        - $ref: '#/components/parameters/IPSid'

      responses:
        '200':
          $ref: '#/components/responses/viewip200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

    post:
      description: Update ACL IP
      summary: "Update information for IP access control list"
      tags:
      - SIP IP Access Control List

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/IPACLSid'
        - $ref: '#/components/parameters/IPSid'

      responses:
        '200':
          $ref: '#/components/responses/viewip200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                FriendlyName:
                  type: string
                  description: A human-readable name associated with this IP ACL. One of FriendlyName or IpAddress is required.
                IpAddress:
                  type: string
                  description: An IP address from which you wish to accept traffic. One of FriendlyName or IpAddress is required.
    delete:
      description: Delete ACL IP
      summary: "deletes IP address from IP access control list"
      tags:
      - SIP IP Access Control List

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/IPACLSid'
        - $ref: '#/components/parameters/IPSid'

      responses:
        '200':
          $ref: '#/components/responses/viewacl200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  parameters:
    IPACLSid:
      in: path
      name: IpAccessControlListSid
      description: >
            IP access control list SID.
      schema:
        type: string
      required: true
    PageSize:
      in: query
      name: PageSize
      description: >
            Used to specify the amount of list items to return per page.
      schema:
        type: integer
      required: false
    Page:
      in: query
      name: Page
      description: >
            Used to return a particular page within the list.
      schema:
        type: integer
      required: false
    AccSid:
      name: AccountSid
      description: >
            Your Account Sid
      in: path
      required: true
      schema:
        type: string
    IPSid:
      name: IpAddressSid
      description: >
            Access control list IP address SID.
      in: query
      required: true
      schema:
        type: string
    FriendlyName:
      name: FriendlyName
      description: >
            Specifies that only IncomingPhoneNumber resources matching the input FriendlyName should be returned in the list request.
      in: query
      required: false
      schema:
        type: string
    MediaExt:
      description: >
            By default, Avaya's REST API returns XML. You may obtain CSV, JSON
            or HTML by appending ".csv", ".json", or ".html".
      in: path
      name: mediaTypeExtension
      required: true
      schema:
        type: string
        enum:
          - .xml
          - .json
          - .csv
          - .html
        default: .xml
    DateCreated:
      name: DateCreated
      description: >
            Lists all recordings created on or after a certain date. Date range can be specified using inequalities like so: DateCreated=>YYYY-MM-DD.
      in: query
      required: false
      schema:
        type: integer

  schemas:
    subresource:
      type: object
      description: URIs for managing this resource.
      properties:
        credentials:
          description: URI for managing credentials on this IP access control list.
          example: /v2/Accounts/{AccountSid}/SIP/IpAccessControlLists/{IPACLSid}/IpAddresses
          type: string

    viewacl:
      type: object
      properties:
        ip_addresses_count:
           type: integer
           description: Number of the assigned IP addresses on this IP access control list.
           example: 1
        subresource_uris:
          $ref: '#/components/schemas/subresource'
        sid:
           type: string
           description: An alphanumeric string identifying this resource.
           example: IpAccessControlListSid
        date_updated:
          type: string
          description: The date the credential list was last updated.
          example: Wed, 17 Jul 2019 17:21:35 -0000
        date_created:
          type: integer
          description: The date this credential list was created.
          example: Wed, 17 Jul 2019 17:20:31 -0000
        friendly_name:
          type: integer
          description: A human-readable name associated with this domain.
          example: NewIpAclList
        uri:
          type: integer
          description: The Uniform Resource Identifier to this resource.
          example: /v2/Accounts/{AccountSid}/SIP/IpAccessControlLists/{IPACLSid}
        account_sid:
          type: integer
          description: An alphanumeric string identifying the account associated with this resource.
          example: AccountSid
    viewip:
      type: object
      properties:
        date_created:
          type: integer
          description: The date this credential list was created.
          example: Wed, 17 Jul 2019 17:20:31 -0000
        subresource_uris:
          $ref: '#/components/schemas/subresource'
        sid:
           type: string
           description: An alphanumeric string identifying this resource.
           example: IpAccessControlListSid
        date_updated:
          type: string
          description: The date the credential list was last updated.
          example: Wed, 17 Jul 2019 17:21:35 -0000
        ip_address:
          type: string
          description: An alphanumeric string identifying the account associated with this resource.
          example: 192.0.0.0
        friendly_name:
          type: integer
          description: A human-readable name associated with this domain.
          example: NewIpAclList
        uri:
          type: integer
          description: The Uniform Resource Identifier to this resource.
          example: /v2/Accounts/{AccountSid}/SIP/IpAccessControlLists/{IPACLSid}/IpAddresses/{IPSid}
        account_sid:
          type: integer
          description: An alphanumeric string identifying the account associated with this resource.
          example: AccountSid
  responses:
    listacl200:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              first_page_uri:
                type: string
                description: URI for the first page of results.
                example: /v2/Accounts/{AccountSid}/SIP/IpAccessControlLists.json?Page=0&amp;PageSize=50
              end:
                type: integer
                description: Last result index.
                example: 3
              total:
                type: integer
                description: Number of items.
                example: 4
              previous_page_uri:
                type: string
                description: URI for the previous page of results.
                example: /v2/Accounts/{AccountSid}/SIP/IpAccessControlLists.json?Page=0&amp;PageSize=50
              num_pages:
                type: integer
                description: Number of pages.
                example: 1
              uri:
                type: string
                description: The Uniform Resource Identifier to this resource.
                example: /v2/Accounts/{AccountSid}/SIP/IpAccessControlLists.json
              page_size:
                type: integer
                description: Number of items on a single page.
                example: 50
              start:
                type: integer
                description: Index of the first item on the current page.
                example: 0
              ip_access_control:
                type: array
                description: Array containing IP access control lists.
                items:
                  $ref: '#/components/schemas/viewacl'
              next_page_uri:
                type: string
                description: URI for the next page of the results.
                example: /v2/Accounts/{AccountSid}/SIP/IpAccessControlLists.json?Page=1&PageSize=50
              last_page_uri:
                type: string
                description: URI for the last page of the results.
                example: /v2/Accounts/{AccountSid}/SIP/IpAccessControlLists.json?Page=1&PageSize=50
              page:
                type: integer
                description: Current page number.
                example: 0
    listip200:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              first_page_uri:
                type: string
                description: URI for the first page of results.
                example: /v2/Accounts/{AccountSid}/SIP/IpAccessControlLists/{ACLSid}/IPAddresses.json?Page=0&amp;PageSize=50
              ip_addresses:
                type: array
                description: Array containing IP addresses.
                items:
                  $ref: '#/components/schemas/viewip'
              end:
                type: integer
                description: Last result index.
                example: 3
              total:
                type: integer
                description: Number of items.
                example: 4
              previous_page_uri:
                type: string
                description: URI for the previous page of results.
                example: /v2/Accounts/{AccountSid}/SIP/IpAccessControlLists/{ACLSid}/IPAddresses.json?Page=0&amp;PageSize=50
              num_pages:
                type: integer
                description: Number of pages.
                example: 1
              uri:
                type: string
                description: The Uniform Resource Identifier to this resource.
                example: /v2/Accounts/{AccountSid}/SIP/IpAccessControlLists/{ACLSid}/IPAddresses.json
              page_size:
                type: integer
                description: Number of items on a single page.
                example: 50
              start:
                type: integer
                description: Index of the first item on the current page.
                example: 0
              next_page_uri:
                type: string
                description: URI for the next page of the results.
                example: /v2/Accounts/{AccountSid}/SIP/IpAccessControlLists/{ACLSid}/IPAddresses.json?Page=1&PageSize=50
              last_page_uri:
                type: string
                description: URI for the last page of the results.
                example: /v2/Accounts/{AccountSid}/SIP/IpAccessControlLists/{ACLSid}/IPAddresses.json?Page=1&PageSize=50
              page:
                type: integer
                description: Current page number.
                example: 0
    viewacl200:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/viewacl"
    viewip200:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/viewip"

    400:
      description: Bad Request
    401:
      description: The supplied credentials, if any, are not sufficient to access the resource.
    404:
      description: The requested resource was not found
    500:
      description: Internal server error.