openapi: 3.0.0

info:
  title: Avaya Onecloud CPaaS
  description: Make communications happen anywhere
  version: "3.0.0"

servers:
  - url: https://api.zang.io/v2
    description: Production server
  - url: https://api.zang.io/v3
    description: Production V3 Beta
  - url: https://api.zangsandbox.com/v2
    description: Sandbox server
  - url: https://api.zangsandbox.com/v3
    description: Sandbox V3 Beta
  - url: https://apik.zang.io/v2
    description: Staging server
  - url: https://apik.zang.io/v3
    description: Staging V3 Beta

paths:
  "/Accounts/{AccountSid}/SMS/Messages{mediaTypeExtension}":
    get:
      description: List SMS
      summary: "shows info on all SMS messages associated with some account"
      tags:
      - SMS

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/To'
        - $ref: '#/components/parameters/From'
        - $ref: '#/components/parameters/DateSent'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'

      responses:
        '200':
          $ref: '#/components/responses/listsms200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    post:
      description: Send SMS
      summary: "send SMS message"
      tags:
      - SMS

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'

      responses:
        '200':
          $ref: '#/components/responses/viewsms200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/reqsms'

  "/Accounts/{AccountSid}/SMS/Messages/{SMSMessageSid}{mediaTypeExtension}":
    get:
      description: View SMS
      summary: "shows info on SMS message"
      tags:
      - SMS

      parameters:
        - $ref: '#/components/parameters/AccSid'
        - $ref: '#/components/parameters/MediaExt'
        - $ref: '#/components/parameters/SmsSid'

      responses:
        '200':
          $ref: '#/components/responses/viewsms200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  parameters:
    To:
      in: query
      name: To
      description: >
            List all SMS sent to this number. The value does not have to be in any specific format.
      schema:
        type: string
      required: false
    From:
      in: query
      name: From
      description: >
            List all SMS sent from this number. The value does not have to be in any specific format.
      schema:
        type: string
      required: false
    DateSent>:
      in: query
      name: DateSent>
      description: >
            Lists all SMS messages sent in a date range. Set DateSent>= and DateSent<= in YYYY-MM-DD format.
      schema:
        type: string
      required: false
      DateSent<:
        in: query
        name: DateSent<
        description: >
        Lists all SMS messages sent in a date range. Set DateSent>= and DateSent<= in YYYY-MM-DD format.
        schema:
          type: string
        required: false
    PageSize:
      in: query
      name: PageSize
      description: >
            Used to specify the amount of list items to return per page.
      schema:
        type: integer
      required: false
    Page:
      in: query
      name: Page
      description: >
            Used to return a particular page within the list.
      schema:
        type: integer
      required: false
    AccSid:
      name: AccountSid
      description: >
            Your Account Sid
      in: path
      required: true
      schema:
        type: string
    SmsSid:
      name: SMSMessageSid
      description: >
            SMS message SID.
      in: path
      required: true
      schema:
        type: string
    MediaExt:
      description: >
            By default, Avaya's REST API returns XML. You may obtain CSV, JSON
            or XML by appending ".csv", ".json", or ".xml".
      in: path
      name: mediaTypeExtension
      required: true
      schema:
        type: string
        enum:
          - .xml
          - .json
          - .csv
        default: .xml
  schemas:
    reqsms:
      type: object
      required:
        - To
        - Body
      properties:
        To:
          type: string
          description: Must be an SMS capable number. E164 format is best practice.
          example: +14166144164
        From:
          type: string
          description: Must be an Avaya CPaaS number associated with your account. If not specified, the SMS will be sent via a random SMS capable number associated with your account. E164 format is best practice.
          example: +14166144164
        Body:
          type: string
          description: Text of the SMS to be sent.
          example: Example text
        StatusCallback:
          type: string
          description: The URL that will be sent information about the SMS. Url length is limited to 200 characters.
          example: www.example.com/statuscallback
        StatusCallbackMethod:
          type: string
          description: The HTTP method used to request the StatusCallback. Valid parameters are GET and POST.
          example: POST
        AllowMultiple:
          type: boolean
          description: Specifies whether you want an SMS that has a body length of over 160 characters to be sent as a concatenated SMS or multipart SMS. Concatenated SMS is not supported for international SMS. Allowed values are true or false.
          example: true
    viewsms:
      type: object
      properties:
        body:
          type: string
          description: Text of the SMS message sent or received. May be up to 160 characters in length.
          example: Test Message.
        status:
          type: string
          description: Status of the SMS; sent, sending, queued, or failed.
          example: sent
        direction:
          type: string
          description: Specifies the direction of the SMS; messages from REST API are “outbound-api”, messages from incoming phone numbers to Avaya CPaaS are “incoming”, messages from InboundXML initiated during an outbound call are “outbound-call”, and messages from InboundXML initiated via an sms reply are “outbound-reply”.
          example: outbound-api
        date_updated:
          type: string
          description: The date the SMS resource was last updated.
          example: Tue, 24 Jul 2012 14:08:24 +0000
        price:
          type: string
          description: Cost of the SMS.
          example: "0.05"
        from:
          type: string
          description: The number that sent the SMS message.
          example: "+14166144164"
        uri:
          type: string
          description: The Uniform Resource Identifier to this resource.
          example: /Accounts/{AccountSid}/SMS/Messages/{SmsSid}
        account_sid:
          type: string
          description: An alphanumeric string identifying the account this call occurred through.
          example: AccountSid
        to:
          type: string
          description: The number that the SMS message was sent to.
          example: "+14166144164"
        sid:
          type: string
          description: An alphanumeric string identifying this resource.
          example: SmsSid
        date_sent:
          type: string
          description: The date the SMS message was sent.
          example: Tue, 24 Jul 2012 14:08:24 +0000
        date_created:
          type: string
          description: The date the SMS resource was created.
          example: Tue, 24 Jul 2012 14:08:23 +0000
        api_version:
          type: string
          description: The Api Version being used.
          example: v2
  responses:
    listsms200:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              page:
                type: integer
                description: Current page number.
                example: 0
              page_size:
                type: integer
                description: Number of items on a single page.
                example: 50
              num_pages:
                type: integer
                description: Number of pages.
                example: 1
              start:
                type: integer
                description: Index of the first item on the current page.
                example: 0
              total:
                type: integer
                description: Number of items.
                example: 4
              end:
                type: integer
                description: Last result index.
                example: 3
              uri:
                type: string
                description: The Uniform Resource Identifier to this resource.
                example: /Accounts/{AccountSid}/SMS/Messages.json
              first_page_uri:
                type: string
                description: URI for the first page of results.
                example: /Accounts/{AccountSid}/SMS/Messages.json?Page=0&PageSize=50
              last_page_uri:
                type: string
                description: URI for the last page of the results.
                example: /Accounts/{AccountSid}/SMS/Messages.json?Page=1&PageSize=50
              next_page_uri:
                type: string
                description: URI for the next page of the results.
                example: /Accounts/{AccountSid}/SMS/Messages.json?Page=1&PageSize=50
              previous_page_uri:
                type: string
                description: URI for the previous page of results.
                example: /Accounts/{AccountSid}/SMS/Messages.json?Page=0&PageSize=50
              sms_messages:
                type: array
                description: Array containing sms messages.
                items:
                  $ref: '#/components/schemas/viewsms'
    viewsms200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/viewsms'
    400:
      description: Bad Request
    401:
      description: The supplied credentials, if any, are not sufficient to access the resource.
    404:
      description: The requested resource was not found
    500:
      description: Internal server error.