openapi: 3.0.0

info:
  title: Avaya Onecloud CPaaS
  description: Make communications happen anywhere
  version: "2.0"

servers:
  - url: https://api.zang.io/v2
    description: Production server

paths:
  '/Accounts/{AccountSid}':
    get:
      description: View Account/Lists Details